### ISSUE TITLE
Debug Version Build

### ISSUE THREAD

**Issue by gspeiliu** [kriztan/Pix-Art-Messenger#499]
I cloned the project and tried to build the debug version via command './gradlew --no-daemon assembleDebug'. However, I cannot build the project successfully, it always pops out the error message as follow:
Pix-Art-Messenger/src/main/java/eu/siacs/conversations/services/AppRTCAudioManager.java:27: error: package org.webrtc does not exist
import org.webrtc.ThreadUtils;
Pix-Art-Messenger/src/main/java/eu/siacs/conversations/xmpp/jingle/JingleRtpConnection.java:17: error: package org.webrtc does not exist
import org.webrtc.EglBase;
Pix-Art-Messenger/src/main/java/eu/siacs/conversations/xmpp/jingle/JingleRtpC$
nnection.java:18: error: package org.webrtc does not exist
import org.webrtc.IceCandidate;
Pix-Art-Messenger/src/main/java/eu/siacs/conversations/xmpp/jingle/WebRTCWrapper.java:28: error: package org.webrtc does not exist
import org.webrtc.DefaultVideoEncoderFactory;
Pix-Art-Messenger/src/main/java/eu/siacs/conversations/xmpp/jingle/WebRTCWrapper.java:90: error: cannot find symbol
    private VideoTrack remoteVideoTrack = null;

I am working on ubuntu 18.04 with java 1.8. Do you have any advice for me?
Thanks

**Comment by kriztan** [comment]
You have to build webrtc library first.
